// <auto-generated />
using System;
using CardGeneratorBackend.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CardGeneratorBackend.Migrations
{
    [DbContext(typeof(CardDatabaseContext))]
    [Migration("20260617204914_CreatedEmbeddingCacheTable")]
    partial class CreatedEmbeddingCacheTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardGeneratorBackend.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("attack");

                    b.Property<Guid?>("CardImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_image_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DisplayImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("display_image_id");

                    b.Property<string>("Effect")
                        .HasColumnType("text")
                        .HasColumnName("effect");

                    b.Property<int?>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Quote")
                        .HasColumnType("text")
                        .HasColumnName("quote");

                    b.Property<Vector>("TextEmbedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("text_embedding");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variant");

                    b.HasKey("Id");

                    b.HasIndex("CardImageId");

                    b.HasIndex("DisplayImageId");

                    b.HasIndex("TypeId");

                    b.ToTable("cards");
                });

            modelBuilder.Entity("CardGeneratorBackend.Entities.CardType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackgroundColorHexCode1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bg_color_hex_code_1");

                    b.Property<string>("BackgroundColorHexCode2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bg_color_hex_code_2");

                    b.Property<Guid?>("ImageFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_color");

                    b.HasKey("Id");

                    b.HasIndex("ImageFileId");

                    b.ToTable("card_types");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BackgroundColorHexCode1 = "ffffff",
                            BackgroundColorHexCode2 = "ffffff",
                            Name = "None",
                            TextColor = "000000"
                        });
                });

            modelBuilder.Entity("CardGeneratorBackend.Entities.DatabaseEmbeddingCacheEntry", b =>
                {
                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("embedded_text");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.HasKey("Text");

                    b.ToTable("embedding_cache_entry");
                });

            modelBuilder.Entity("CardGeneratorBackend.Entities.GlobalState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ShouldUpdateCardEmbeddings")
                        .HasColumnType("boolean")
                        .HasColumnName("should_update_card_embeddings");

                    b.HasKey("Id");

                    b.ToTable("global_state");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ShouldUpdateCardEmbeddings = true
                        });
                });

            modelBuilder.Entity("CardGeneratorBackend.Entities.TrackedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_location");

                    b.HasKey("Id");

                    b.ToTable("tracked_files");
                });

            modelBuilder.Entity("CardGeneratorBackend.Entities.Card", b =>
                {
                    b.HasOne("CardGeneratorBackend.Entities.TrackedFile", "CardImage")
                        .WithMany()
                        .HasForeignKey("CardImageId");

                    b.HasOne("CardGeneratorBackend.Entities.TrackedFile", "DisplayImage")
                        .WithMany()
                        .HasForeignKey("DisplayImageId");

                    b.HasOne("CardGeneratorBackend.Entities.CardType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardImage");

                    b.Navigation("DisplayImage");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CardGeneratorBackend.Entities.CardType", b =>
                {
                    b.HasOne("CardGeneratorBackend.Entities.TrackedFile", "ImageFile")
                        .WithMany()
                        .HasForeignKey("ImageFileId");

                    b.Navigation("ImageFile");
                });
#pragma warning restore 612, 618
        }
    }
}
